services:
    keosu_gadget.menu.search:
        class: Keosu\Gadget\SearchGadgetBundle\EventListener\GadgetListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }
