services:
    keosu_gadget.menu.export:
        class: Keosu\Gadget\BaseBundle\EventListener\ExportListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }
