keosu_gadget_pictures_gallery_gadget_add:
    path:  /views/page/gadget/picturesgallerygadget/add/{page}/{zone}
    defaults: { _controller: KeosuGadgetPicturesGalleryGadgetBundle:Edit:add }
    
keosu_gadget_pictures_gallery_gadget_edit:
    path:  /views/page/gadget/picturesgallerygadget/edit/{page}/{zone}
    defaults: { _controller: KeosuGadgetPicturesGalleryGadgetBundle:Edit:edit }
    
keosu_gadget_pictures_gallery_service:
    path:  /service/gadget/picturesgallery/{gadgetId}/{offset}/{format}
    defaults: { _controller: KeosuGadgetPicturesGalleryGadgetBundle:Service:viewList }
