parameters:
#    keosu_gadget_pictures_gallery_gadget.example.class: Keosu\Gadget\PicturesGalleryGadgetBundle\Example

services:
#    keosu_gadget_pictures_gallery_gadget.example:
#        class: %keosu_gadget_pictures_gallery_gadget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
