keosu_location_viewlist:
    path:  /content/poi/
    defaults: { _controller: KeosuDataModelLocationModelBundle:View:view }
    
keosu_poi_delete:
    path:  /content/poi/delete/{id}
    defaults: { _controller: KeosuDataModelLocationModelBundle:Edit:delete }
    
keosu_poi_edit:
    path:  /content/poi/edit/{id}
    defaults: { _controller: KeosuDataModelLocationModelBundle:Edit:edit }
    
keosu_poi_add:
    path:  /content/poi/add
    defaults: { _controller: KeosuDataModelLocationModelBundle:Edit:add }
