keosu_article_viewlist:
    path:  /content/article/
    defaults: { _controller: KeosuDataModelArticleModelBundle:View:view }
    
keosu_article_delete:
    path:  /content/article/delete/{id}
    defaults: { _controller: KeosuDataModelArticleModelBundle:Edit:delete }
    
keosu_article_edit:
    path:  /content/article/edit/{id}
    defaults: { _controller: KeosuDataModelArticleModelBundle:Edit:edit }
    
keosu_article_add:
    path:  /content/article/add
    defaults: { _controller: KeosuDataModelArticleModelBundle:Edit:add }

