keosu_gadget_authentication_gadget_add:
    path:  /views/page/gadget/authenticationgadget/add/{page}/{zone}
    defaults: { _controller: KeosuGadgetAuthenticationGadgetBundle:Edit:add }

keosu_gadget_authentication_gadget_edit:
    path:  /views/page/gadget/authenticationgadget/edit/{page}/{zone}
    defaults: { _controller: KeosuGadgetAuthenticationGadgetBundle:Edit:edit }

keosu_gadget_authentication_reset_success:
    path:  /resetting/success
    defaults: { _controller: KeosuGadgetAuthenticationGadgetBundle:Reset:success }

keosu_gadget_authentication_service_init:
    path:  /service/gadget/authentication/{gadgetId}/{format}/init
    defaults: { _controller: KeosuGadgetAuthenticationGadgetBundle:Service:init }

keosu_gadget_authentication_service_loginInit:
    path:  /service/gadget/authentication/{gadgetId}/{format}/loginInit
    defaults: { _controller: KeosuGadgetAuthenticationGadgetBundle:Service:loginInit }

keosu_gadget_authentication_service_logout:
    path:  /service/gadget/authentication/{gadgetId}/logout
    defaults: { _controller: KeosuGadgetAuthenticationGadgetBundle:Service:logout }

keosu_gadget_authentication_service_register:
    path:  /service/gadget/authentication/{gadgetId}/{format}/register
    defaults: { _controller: KeosuGadgetAuthenticationGadgetBundle:Service:register }

keosu_gadget_authentication_service_forgotPassword:
    path:  /service/gadget/authentication/{gadgetId}/{format}/forgotPassword
    defaults: { _controller: KeosuGadgetAuthenticationGadgetBundle:Service:forgotPassword }
