services:
    keosu_gadget.last.article.gadget:
        class: Keosu\Gadget\LastArticleGadgetBundle\EventListener\GadgetListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }

