services:
    keosu_gadget.picture.gadget:
        class: Keosu\Gadget\PictureGadgetBundle\EventListener\GadgetListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }

